### ISSUE TITLE
text-anchor="end" ignored on last text element

### ISSUE THREAD

**Issue by awerlang** [alafr/SVG-to-PDFKit#27]
See this snippet:

```
<svg xml:space="preserve" xmlns:xlink="http://www.w3.org/1999/xlink" preserveAspectRatio="xMinYMin meet" version="1.1" viewBox="0 0 600 480" width="100%" x="0px" xmlns="http://www.w3.org/2000/svg" y="0px">
    <text fill="#828282" font-family="Arial" font-size="10" text-anchor="end">
        <tspan dominant-baseline="middle" x="50" y="110">450</tspan>
        <tspan dominant-baseline="middle" x="50" y="158">400</tspan>
        <tspan dominant-baseline="middle" x="50" y="206">350</tspan>
        <tspan dominant-baseline="middle" x="50" y="254">300</tspan>
        <tspan dominant-baseline="middle" x="50" y="302">250</tspan>
    </text>
</svg>
```

The last text item ("250") isn't properly aligned to the column. To my surprise I got the same result with individual `<text>`. To work around that, I'm adding another `<tspan>` containing a space.

On the demo page, checking the box "Insert the SVG in the document and use the computed style" I get the correct result.

**Comment by alafr** [comment]
It's because of the `xml:space="preserve"` attribute. The indentation between the `tspan`s is white space and it affects the alignment (the last item has fewer spaces after it). It looks the same in Firefox (apparently Chrome has no support for this attribute).

But even with `xml:space="default"` there is a smaller (but visible) misalignment, I will debug this as soon as possible...

**Comment by awerlang** [comment]
Indeed, removing it fix this issue for me.

Thanks!
