### ISSUE TITLE
useCSS option failing

### ISSUE THREAD

**Issue by josecolella** [alafr/SVG-to-PDFKit#47]
Hello,
First of all I wanted to thank you for this. Makes using pdfkit much easier. I am receiving the following message when trying to convert an svg with styles to a pdf document:

> SVGtoPDF: useCSS option can only be used for SVG *elements* in compatible browsers

I have tried to use your demo site and it works perfectly with the useCSS option.

Here is a link to the gist. https://gist.github.com/josecolella/adc2e835a84a148b441b37453b54f064

**Comment by jokester** [comment]
Experienced a similar problem. It turns out that in *Chrome*, `someEmbedElement.getSVGDocument().firstElementChild` may be a object that don't `instanceof` SVGElement (yet still supports `getComputedStyle`). So useCSS is forced to be false on such elements. See [this](https://gistcdn.githack.com/jokester/c1fccc52fb7c5facb8f7151073421041/raw/9455355a06136c83f38edecb3e2a7f7c6bba3ff2/alien-object.html) for a minimal example. 

This only happens in Chrome (at least not in Firefox).It looks more likely a browser bug to me though.

**Comment by jokester** [comment]
Found a workaroud for previous comment: we can fix its prototype manually

    Object.setPrototype(SVGSVGElement.prototype, theAlienObject);
    SVGtoPDF(doc, theAlienObject, 0, 0, { useCSS: true });

**Comment by josecolella** [comment]
Thanks @jokester. Works now

**Comment by dingchao-95** [comment]
Hi i was wondering if anyone could help with my issue, i'm facing the same thing as @josecolella , here is my issue with documented details : https://github.com/alafr/SVG-to-PDFKit/issues/97
@jokester @alafr
